# Generated by Django 3.1.7 on 2021-03-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemindersClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('msg', models.CharField(max_length=200)),
                ('reminderdt', models.DateTimeField(verbose_name='reminderdt')),
                ('emailaddr', models.CharField(max_length=200)),
            ],
        ),
    ]
